-- liquibase formatted sql
--
-- changeSet Anatoly:1
CREATE TABLE UserEntity(
id int generated by default as identity primary key,
role text,
username text unique,
password text,
firstName text,
lastName text,
phone text,
);