-- liquibase formatted sql
--
-- changeSet Anatoly:1
CREATE TABLE UserEntity(
id int generated by default as identity primary key,
role text,
username text unique,
password text,
firstName text,
lastName text,
phone text,
);

-- changeSet Konstantin:2
        CREATE TABLE ads(
                id int generated by default as identity primary key,
                author_id int,
                title text,
                description text,
                price int,
                createdAt date
        );

-- changeSet Konstantin:3
        CREATE TABLE ads_image(
                id int generated by default as identity primary key,
                ads_id int,
                data byte,
                fileSize bigint,
                filePath text,
                contentType text
        );